### ISSUE TITLE
Restconn Badges

### ISSUE THREAD

**Issue by ipsilantide** [RestComm/design#146]
We need to create a design for our Restconn badges. Same will be provided to each one of the speakers and telestax employees.

deadline: April 27
opened by: Desi Pepova 
![img_20170423_124147_1024 2](https://cloud.githubusercontent.com/assets/17202395/25344902/30b26ff2-291c-11e7-805c-ac7bc0fbacec.jpg)

**Comment by desipepova** [comment]
Dimensions
Width:  75 mm
Height: 100 mm

**Comment by radkayordanova** [comment]
Here is the new design: https://drive.google.com/drive/folders/0ByPD1Seb_T5jOXFvbFozWHZJUEU
