### ISSUE TITLE
When searching for numbers the error message should appear vertically centered 

### ISSUE THREAD

**Issue by otsakir** [RestComm/design#61]
![adminui_issue3](https://cloud.githubusercontent.com/assets/8972800/21424710/31c56974-c84d-11e6-99d6-8c2d07c24cf8.png)

**Comment by ipsilantide** [comment]
Issue moved to [RestComm/Restcomm-Connect #1868](https://github.com/RestComm/Restcomm-Connect/issues/1868) via [**ZenHub**](https://www.zenhub.com/)
