### ISSUE TITLE
 Design Restcomm-connect’s empty state

### ISSUE THREAD

**Issue by deruelle** [RestComm/design#65]
Empty state is when user log’s in for first time to Restcomm-connect admin panel and there is no data to show. Let’s make empty states helpful by telling user to register their first number, create app via Restcomm Visual Designer etc.

**Comment by ipsilantide** [comment]
Issue moved to [RestComm/Restcomm-Connect #1866](https://github.com/RestComm/Restcomm-Connect/issues/1866) via [**ZenHub**](https://www.zenhub.com/)
