### ISSUE TITLE
Restcomm Olympus, RVD, Dashboard What's new

### ISSUE THREAD

**Issue by deruelle** [RestComm/design#66]
Like slack has “What's New”, may be every new feature can be hinted to user when they login to Restcomm-connect dashboard?

Send email to existing users about new version rolled out in Restcomm cloud with cool new features?

**Comment by ipsilantide** [comment]
Yes we need something like that

**Comment by ipsilantide** [comment]
Issue moved to [RestComm/Restcomm-Connect #1865](https://github.com/RestComm/Restcomm-Connect/issues/1865) via [**ZenHub**](https://www.zenhub.com/)
