### ISSUE TITLE
`Administrator` Role disappears from dropdown after choosing `Developer`

### ISSUE THREAD

**Issue by maria-farooq** [RestComm/design#69]
@ipsilantide in admin UI
- Click on `Create new Account`
- in drop down you will see 2 options for `Role` i chose `Developer` and `Administrator`
- click on `Developer`.
- now click on drop down again
- you will see  `Administrator` disappears from it.

**Comment by ipsilantide** [comment]
I add dashboard instead of dashboard ux since UX we will use for the new final one

**Comment by ipsilantide** [comment]
Moved in Restcomm-connect
